#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=24:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node 
#SBATCH --mem=125G   # maximum memory per node
#SBATCH --job-name="extract_by_length"
#SBATCH --mail-user=dlavrov@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

FilterByLength/FilterByLength.py -l 3000 -m 7000 -i /ptmp/LAS/dlavrov-lab/ERR12319363.fasta -o ERR12319363_3-7K.fasta > temp.fasta
