#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=24:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=32   # 16 processor core(s) per node 
#SBATCH --mem=125G   # maximum memory per node
#SBATCH --job-name="dl-cap3"
#SBATCH --mail-user=dlavrov@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

module load trnascan-se/2.0.11-apgeqbb
./tRNAscan.sh reads_with_repeats_no_genes.fa.cap.all.fa 
